[tools]
python = "3.11"
uv = "0.6.5"

[env]
_.python.venv = { path = ".venv", create = true, uv_create_args = ['--seed']}



[tasks.install-deps]
description = "install dependencies"
run = [
    "uv pip install -r requirements.txt",
    "git secrets --install",
    "git secrets --register-aws",
    "detect-secrets scan > .secrets.baseline",
]

